### PR TITLE
Minor edits to make it compatible with bash

### PR DESCRIPTION
**Pull request by hsheth2**

### CODE REVIEW

**Comment by benvan** [comment]
Hi @hsheth2, thanks for the pull request

Can I suggest instead wrapping the bottom section (# create hooks for the sandbox names themselves) in a function and leaving the local declarations? This will prevent these changes from potentially breaking people's scripts which might use `func` or `cmd` as variables and having them unset by sandboxd

**Comment by hsheth2** [comment]
It looks like I sent this PR a bit prematurely; my changes don't seem to work fully. I'll take another look and update the PR when I get a chance.

**Comment by erikw** [comment]
@hsheth2 Did you get a chance to take another look? Would be great to have bash support working! :)

**Comment by hsheth2** [comment]
@erikw I'm actually not using sandboxd anymore, so I haven't really followed up with this. From what I remember, the simplest way to work around the issue in bash was to disable the feature in which hooks are created for the sandbox name itself (currently around line 50), and simply do that step manually in your `.sandboxrc` file.

**Comment by MoOx** [comment]
@hsheth2 curious to know what you use instead of this script to lazy load heavy stuff in your *rc/profile

**Comment by benvan** [comment]
@MoOx @erikw  I've added bash support to this branch: https://github.com/benvan/sandboxd/tree/bash-support

It seems to work as far as I've tested it so far - would you let me know if you have any trouble?

**Comment by hsheth2** [comment]
@MoOx I don't use anything for lazy loading now. The combination of removing cruft and buying a new laptop has reduced my shell startup time to approximately 0.2 seconds.

**Comment by hsheth2** [comment]
I would direct future discussion on this issue to #5 and to @benvan's `bash-support` branch.

**Pull request closed without merging**
